"""Ticket Priority Auditor - Streamlit front end.

Three ways to use it:
  1. Single ticket  - fill a short form, get one verdict
  2. Batch CSV      - upload a tickets CSV, score every row
  3. Dashboard      - Priority Mismatch Dashboard with distribution of flagged
                      tickets, mismatch types, top contributing signals, and a
                      severity delta heatmap across ticket categories and channels.

Every analysis now produces nine fields:
  Ticket_ID, prediction, confidence, mismatch_type, dossier_json,
  category, channel, severity_delta, keywords

This file only READS from predict.py (TicketPredictor + PRIORITY_MAP).
It does not import or run train_pipeline.py.

Deploy notes:
  - The trained model, tokenizer, and encoders are NOT committed to the repo.
    On first boot this app downloads them from the Hugging Face Hub repo set in
    HF_REPO into MODEL_DIR (default ./saved_model), so a GitHub-only deploy works.
  - Dossier analysis is generated by the Mistral API. Set MISTRAL_API_KEY in
    Streamlit Secrets (or the environment). The deterministic template is used
    only as an automatic fallback if an API call fails, so the app never breaks.
"""

import os
import json
import urllib.request
import urllib.error

import numpy as np
import pandas as pd
import streamlit as st

try:
    import plotly.graph_objects as go
    import plotly.express as px
    _PLOTLY = True
except ImportError:
    _PLOTLY = False

from predict import TicketPredictor, PRIORITY_MAP, PRIORITY_INVERSE

MODEL_DIR = os.environ.get("MODEL_DIR", "saved_model")
HF_REPO = os.environ.get("HF_REPO", "Rishabh-Singhal15/support-integrity-auditor")

# Nine output fields — category, channel, severity_delta, keywords added for
# the Dashboard heatmap and signals chart.
OUTPUT_COLS = [
    "Ticket_ID", "prediction", "confidence", "mismatch_type", "dossier_json",
    "category", "channel", "severity_delta", "keywords",
]

# Generative dossier configuration (all overridable by env var / Streamlit Secrets).
#   DOSSIER_BACKEND: mistral_api | local_mistral | template
#   mistral_api   -> default; fast, needs MISTRAL_API_KEY, best for CPU deploys
#   local_mistral -> runs Mistral-7B locally (faithful to the notebook, needs a GPU)
#   template      -> the deterministic predict.py dossier, no LLM
# Mistral is the default. If an API call fails you can switch to Local or Template
# from the sidebar; the app also auto-falls back to the template so it never breaks.
DEFAULT_BACKEND = os.environ.get("DOSSIER_BACKEND", "mistral_api")
MISTRAL_API_KEY = os.environ.get("MISTRAL_API_KEY", "")
MISTRAL_API_MODEL = os.environ.get("MISTRAL_API_MODEL", "mistral-small-latest")
LOCAL_MISTRAL_MODEL = os.environ.get("LOCAL_MISTRAL_MODEL", "mistralai/Mistral-7B-Instruct-v0.3")
BACKEND_LABELS = {
    "mistral_api": "Mistral API (generative, default)",
    "local_mistral": "Local Mistral 7B (generative, slow, needs GPU)",
    "template": "Template (instant, no LLM)",
}

st.set_page_config(
    page_title="MARS · Ticket Priority Auditor",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="collapsed",
)


# Fall back to .streamlit/secrets.toml for any config not set in the environment,
# so the keys can be set once in Streamlit Secrets instead of exported each session.
def _from_secrets(name):
    try:
        if name in st.secrets:
            return str(st.secrets[name])
    except Exception:  # noqa: BLE001  (no secrets.toml present, etc.)
        pass
    return ""


if not MISTRAL_API_KEY:
    MISTRAL_API_KEY = _from_secrets("MISTRAL_API_KEY")
if os.environ.get("DOSSIER_BACKEND") is None and _from_secrets("DOSSIER_BACKEND"):
    DEFAULT_BACKEND = _from_secrets("DOSSIER_BACKEND")
if os.environ.get("MISTRAL_API_MODEL") is None and _from_secrets("MISTRAL_API_MODEL"):
    MISTRAL_API_MODEL = _from_secrets("MISTRAL_API_MODEL")

# Only needed if the Hugging Face repo is private. None is fine for public repos.
HF_TOKEN = os.environ.get("HF_TOKEN", "") or _from_secrets("HF_TOKEN") or None

st.markdown(
    """
    <style>
      /* ── Google Font ── */
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

      /* ── Global reset ── */
      html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

      /* ── Page background: deep slate ── */
      .stApp { background: #0f1117; }

      /* ── Main content area ── */
      .block-container {
        padding-top: 1.6rem !important;
        padding-bottom: 3rem !important;
        max-width: 1200px;
      }

      /* ── Top nav-bar branding strip ── */
      .mars-navbar {
        display: flex;
        align-items: center;
        gap: 14px;
        padding: 14px 0 18px 0;
        border-bottom: 1px solid #1e2435;
        margin-bottom: 24px;
      }
      .mars-logo {
        font-size: 1.55rem;
        font-weight: 700;
        color: #ffffff;
        letter-spacing: -0.5px;
      }
      .mars-logo span { color: #6366f1; }
      .mars-tagline {
        font-size: 0.82rem;
        color: #6b7280;
        margin-top: 2px;
        letter-spacing: 0.2px;
      }
      .mars-badge {
        margin-left: auto;
        background: #1e2435;
        border: 1px solid #2d3550;
        color: #818cf8;
        font-size: 0.72rem;
        font-weight: 600;
        padding: 3px 10px;
        border-radius: 20px;
        letter-spacing: 0.5px;
        text-transform: uppercase;
      }

      /* ── Tabs: professional top-nav style ── */
      .stTabs [data-baseweb="tab-list"] {
        background: #161b2e;
        border-radius: 10px;
        padding: 4px;
        gap: 2px;
        border: 1px solid #1e2a45;
        margin-bottom: 24px;
      }
      .stTabs [data-baseweb="tab"] {
        font-size: 0.88rem;
        font-weight: 500;
        color: #9ca3af !important;
        background: transparent !important;
        border-radius: 7px !important;
        padding: 8px 20px !important;
        border: none !important;
        transition: all 0.18s ease;
      }
      .stTabs [data-baseweb="tab"]:hover {
        color: #c7d2fe !important;
        background: #1e2a45 !important;
      }
      .stTabs [aria-selected="true"] {
        background: #6366f1 !important;
        color: #ffffff !important;
        font-weight: 600 !important;
        box-shadow: 0 2px 12px rgba(99,102,241,0.35) !important;
      }
      .stTabs [data-baseweb="tab-highlight"] { display: none !important; }
      .stTabs [data-baseweb="tab-border"]    { display: none !important; }

      /* ── Cards / form containers ── */
      .stForm {
        background: #161b2e;
        border: 1px solid #1e2a45;
        border-radius: 12px;
        padding: 20px 24px;
      }

      /* ── Inputs & selects ── */
      .stTextInput > div > div > input,
      .stTextArea > div > div > textarea,
      .stSelectbox > div > div {
        background: #0f1117 !important;
        border: 1px solid #2d3550 !important;
        border-radius: 7px !important;
        color: #e2e8f0 !important;
      }
      .stTextInput > div > div > input:focus,
      .stTextArea > div > div > textarea:focus {
        border-color: #6366f1 !important;
        box-shadow: 0 0 0 3px rgba(99,102,241,0.2) !important;
      }

      /* ── Primary button ── */
      .stButton > button[kind="primary"],
      .stFormSubmitButton > button {
        background: linear-gradient(135deg, #6366f1, #4f46e5) !important;
        border: none !important;
        border-radius: 8px !important;
        color: #ffffff !important;
        font-weight: 600 !important;
        font-size: 0.875rem !important;
        padding: 8px 22px !important;
        box-shadow: 0 2px 12px rgba(99,102,241,0.35) !important;
        transition: opacity 0.15s ease !important;
      }
      .stButton > button[kind="primary"]:hover,
      .stFormSubmitButton > button:hover {
        opacity: 0.88 !important;
      }

      /* ── Secondary button ── */
      .stButton > button:not([kind="primary"]) {
        background: #1e2a45 !important;
        border: 1px solid #2d3550 !important;
        border-radius: 8px !important;
        color: #c7d2fe !important;
        font-weight: 500 !important;
      }

      /* ── Metric cards ── */
      [data-testid="stMetric"] {
        background: #161b2e;
        border: 1px solid #1e2a45;
        border-radius: 10px;
        padding: 14px 18px !important;
      }
      [data-testid="stMetricLabel"] { color: #9ca3af !important; font-size: 0.78rem !important; }
      [data-testid="stMetricValue"] { color: #f1f5f9 !important; font-size: 1.55rem !important; font-weight: 700 !important; }

      /* ── Alert / info / success / error ── */
      .stAlert {
        border-radius: 8px !important;
        border-left-width: 4px !important;
      }

      /* ── Expander ── */
      .streamlit-expanderHeader {
        background: #161b2e !important;
        border-radius: 8px !important;
        color: #c7d2fe !important;
      }

      /* ── Dataframe ── */
      .stDataFrame { border-radius: 10px; overflow: hidden; }

      /* ── Divider ── */
      hr { border-color: #1e2a45 !important; margin: 1.5rem 0 !important; }

      /* ── Section headings ── */
      h1 { color: #f1f5f9 !important; font-weight: 700 !important; letter-spacing: -0.5px !important; }
      h2, h3 { color: #e2e8f0 !important; font-weight: 600 !important; }

      /* ── Sidebar collapse (keep it minimal) ── */
      [data-testid="collapsedControl"] { display: none; }
      section[data-testid="stSidebar"] {
        background: #161b2e;
        border-right: 1px solid #1e2a45;
      }
      section[data-testid="stSidebar"] * { color: #c7d2fe !important; }

      /* ── Helper text ── */
      .legend { color: #6b7280; font-size: 0.84rem; line-height: 1.7; }
      .heatmap-legend { font-size: 0.82rem; color: #6b7280; line-height: 1.8; }

      /* ── Progress bar ── */
      .stProgress > div > div { background: #6366f1 !important; }

      /* ── Download button ── */
      .stDownloadButton > button {
        background: #1e2a45 !important;
        border: 1px solid #2d3550 !important;
        border-radius: 8px !important;
        color: #818cf8 !important;
        font-weight: 500 !important;
      }
    </style>
    """,
    unsafe_allow_html=True,
)


# --------------------------------------------------------------------------- #
# Model files: pull from the Hugging Face Hub on first run (cached per session)
# --------------------------------------------------------------------------- #
@st.cache_resource(show_spinner="Downloading model from Hugging Face (first run only)...")
def ensure_model_files(model_dir, repo_id, token):
    """Download model.pt, the tokenizer/, and the .pkl encoders from the Hub
    into model_dir if they are not already present. The big files live on the
    Hub, not in the git repo, which is what makes a clean GitHub deploy work."""
    from huggingface_hub import snapshot_download

    if not os.path.exists(os.path.join(model_dir, "model.pt")):
        snapshot_download(
            repo_id=repo_id,
            local_dir=model_dir,
            token=token,
            allow_patterns=["model.pt", "*.pkl", "tokenizer/*"],
        )
    return model_dir


# --------------------------------------------------------------------------- #
# Model loading (cached so it loads once per session)
# --------------------------------------------------------------------------- #
@st.cache_resource(show_spinner="Loading model and encoders...")
def load_predictor(model_dir):
    return TicketPredictor(model_dir=model_dir)


try:
    ensure_model_files(MODEL_DIR, HF_REPO, HF_TOKEN)
    predictor = load_predictor(MODEL_DIR)
except Exception as exc:  # noqa: BLE001
    st.title("Ticket Priority Auditor")
    st.error(
        f"Could not download or load the model.\n\n"
        f"```\n{exc}\n```\n\n"
        f"Checked Hugging Face repo `{HF_REPO}` and local folder `{MODEL_DIR}`. "
        "If the repo is private, add an `HF_TOKEN` secret. Otherwise make sure "
        "model.pt, tokenizer/, and the three .pkl encoders exist on the Hub."
    )
    st.stop()


# --------------------------------------------------------------------------- #
# Dropdown options come from the model's own encoders, so they always match
# what it was trained on. Fall back to sensible defaults if unavailable.
# --------------------------------------------------------------------------- #
def encoder_options(encoder, fallback):
    try:
        return [str(c) for c in encoder.classes_]
    except Exception:  # noqa: BLE001
        return fallback


CATEGORY_OPTS = encoder_options(predictor.category_encoder, ["Billing", "Technical issue", "Account access"])
CHANNEL_OPTS = encoder_options(predictor.channel_encoder, ["Email", "Chat", "Phone", "Social media"])
PRIORITY_OPTS = list(PRIORITY_MAP.keys())


# --------------------------------------------------------------------------- #
# Shared helpers
# --------------------------------------------------------------------------- #
def reconcile_verdict(result):
    """Re-derive verdict + mismatch so a direction is only reported when the
    keyword-vs-priority gap actually supports it.

    predict.py marks a mismatch on the model flag alone and, when the keyword
    delta is 0, guesses a direction from resolution time. That can produce
    impossible labels (e.g. "False Alarm" on a Low-priority ticket, which has
    nothing lower to be over-prioritized against). Here a mismatch needs the
    rule delta to point a direction; the model flag refines within it, and a
    large gap (|delta| >= 2) still triggers on its own."""
    rule = result["rule"]
    delta = rule["severity_delta"]
    model_flag = result["model"]["label"] == "Mismatch"

    if delta > 0 and (model_flag or delta >= 2):
        verdict, is_mismatch = "Hidden Crisis", True
    elif delta < 0 and (model_flag or delta <= -2):
        verdict, is_mismatch = "False Alarm", True
    else:
        verdict, is_mismatch = "Consistent", False

    # Keep the reported confidence aligned with the reconciled decision.
    model = result["model"]
    if is_mismatch:
        model["confidence"] = round(float(model.get("mismatch_probability", model["confidence"])), 4)
    else:
        model["confidence"] = round(float(model.get("consistent_probability", model["confidence"])), 4)

    result["verdict"] = verdict
    result["is_mismatch"] = is_mismatch
    return result


def build_dossier_schema(ticket_id, result):
    """Assemble the structured dossier. All data fields come from the model
    result (always correct); constraint_analysis is the one generative field
    (Mistral-written when the API is reachable, template text otherwise)."""
    rule = result["rule"]
    inp = result["input"]
    evidence = rule["evidence"]
    res_norm = float(rule.get("resolution_time_norm", 0.0))
    res_hours = inp.get("resolution_hours", 0.0)

    if res_norm >= 0.5:
        res_interp = "above-median handling time, which leans under-prioritized"
    else:
        res_interp = "below-median handling time, consistent with lower urgency"

    return {
        "ticket_id": ticket_id,
        "assigned_priority": rule["assigned_priority"],
        "inferred_severity": PRIORITY_INVERSE.get(
            rule["inferred_severity"], str(rule["inferred_severity"])
        ),
        "mismatch_type": result["verdict"],
        "severity_delta": rule["severity_delta"],
        "feature_evidence": [
            {
                "signal": "keyword",
                "value": ", ".join(evidence) if evidence else "none",
                "weight": rule["inferred_severity"],
            },
            {
                "signal": "resolution_time",
                "value": res_hours,
                "interpretation": res_interp,
            },
        ],
        "constraint_analysis": result.get("analysis", result.get("dossier", "")),
        "confidence": round(float(result["model"]["confidence"]), 4),
    }


def result_to_row(ticket_id, result):
    """Collapse a predictor result into the nine output fields.

    The four new fields — category, channel, severity_delta, keywords — feed
    the Dashboard tab's heatmap and top-signals chart.
    """
    schema = build_dossier_schema(ticket_id, result)
    evidence = result["rule"]["evidence"]
    return {
        "Ticket_ID": ticket_id,
        "prediction": "Mismatch" if result["is_mismatch"] else "Consistent",
        "confidence": round(float(result["model"]["confidence"]), 4),
        "mismatch_type": result["verdict"],
        "dossier_json": json.dumps(schema, ensure_ascii=False),
        # --- new fields ---
        "category": result["input"].get("category", ""),
        "channel": result["input"].get("channel", ""),
        "severity_delta": int(result["rule"]["severity_delta"]),
        "keywords": ", ".join(evidence) if evidence else "",
    }


def store_rows(rows):
    """Append rows to the session-wide results table (drives the Dashboard tab)."""
    new = pd.DataFrame(rows, columns=OUTPUT_COLS)
    if "results" not in st.session_state:
        st.session_state["results"] = new
    else:
        existing = st.session_state["results"]
        # Fill any missing columns that older rows may not have
        for col in OUTPUT_COLS:
            if col not in existing.columns:
                existing[col] = ""
        st.session_state["results"] = pd.concat(
            [existing, new], ignore_index=True
        )


def verdict_banner(verdict):
    if verdict == "Hidden Crisis":
        st.error("🔴 Hidden Crisis — ticket looks under-prioritized.")
    elif verdict == "False Alarm":
        st.warning("🟡 False Alarm — ticket looks over-prioritized.")
    else:
        st.success("✅ Consistent — assigned priority matches the content.")


def find_col(df, candidates):
    """Return the first column in df that matches any candidate (case-insensitive)."""
    lower = {c.lower(): c for c in df.columns}
    for cand in candidates:
        if cand.lower() in lower:
            return lower[cand.lower()]
    return None


# --------------------------------------------------------------------------- #
# Generative dossier via Mistral API (predict.py is untouched)
# --------------------------------------------------------------------------- #
def _dossier_prompt(result):
    inp, rule = result["input"], result["rule"]
    evidence = ", ".join(rule["evidence"]) if rule["evidence"] else "none"
    return (
        f"Ticket subject: {inp['subject']}\n"
        f"Description: {inp['description']}\n"
        f"Assigned priority: {rule['assigned_priority']}\n"
        f"Model verdict: {result['verdict']} (mismatch={result['is_mismatch']})\n"
        f"Inferred severity 0-3: {rule['inferred_severity']}; "
        f"assigned 0-3: {rule['assigned_priority_num']}; gap: {rule['severity_delta']}\n"
        f"Severity keywords found: {evidence}\n"
        f"Resolution time (hours): {inp['resolution_hours']}\n\n"
        "Write a 2-3 sentence analyst assessment: state whether the ticket is "
        "correctly prioritized, why (cite the content signals above), and the "
        "recommended action. Plain prose, no greeting, no lists."
    )


def _mistral_api_dossier(result):
    if not MISTRAL_API_KEY:
        raise RuntimeError("MISTRAL_API_KEY is not set")
    payload = json.dumps({
        "model": MISTRAL_API_MODEL,
        "messages": [
            {"role": "system", "content": "You are a concise support operations analyst."},
            {"role": "user", "content": _dossier_prompt(result)},
        ],
        "temperature": 0.3,
        "max_tokens": 220,
    }).encode("utf-8")
    req = urllib.request.Request(
        "https://api.mistral.ai/v1/chat/completions",
        data=payload,
        headers={
            "Authorization": f"Bearer {MISTRAL_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["choices"][0]["message"]["content"].strip()


@st.cache_resource(show_spinner="Loading local Mistral 7B (first load is slow)...")
def _load_local_mistral(model_name):
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM

    tok = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
        device_map="auto" if torch.cuda.is_available() else None,
    )
    return tok, model


def _local_mistral_dossier(result):
    import torch

    tok, model = _load_local_mistral(LOCAL_MISTRAL_MODEL)
    messages = [{"role": "user", "content": _dossier_prompt(result)}]
    inputs = tok.apply_chat_template(messages, return_tensors="pt", add_generation_prompt=True)
    inputs = inputs.to(model.device)
    with torch.no_grad():
        out = model.generate(
            inputs, max_new_tokens=220, temperature=0.3,
            do_sample=True, pad_token_id=tok.eos_token_id,
        )
    return tok.decode(out[0][inputs.shape[1]:], skip_special_tokens=True).strip()


def generate_dossier(result, backend):
    """Return (analysis_text, source).

    backend == "mistral_api"   -> default; generative analysis from the Mistral API.
    backend == "local_mistral" -> generative analysis from a local Mistral 7B (GPU).
    backend == "template"      -> instant deterministic predict.py text, no LLM.

    On any LLM failure we fall back to the template so the app never breaks, and
    the reason is shown inline. If the API fails you can also switch the mode in
    the sidebar to Local or Template for subsequent runs."""
    if backend == "template":
        return result["dossier"], "template"
    try:
        if backend == "mistral_api":
            return _mistral_api_dossier(result), "mistral-api"
        if backend == "local_mistral":
            return _local_mistral_dossier(result), "local-mistral"
    except Exception as exc:  # noqa: BLE001
        return (
            result["dossier"]
            + f"\n\n[{backend} unavailable, showing template fallback: {exc}. "
            "Switch the analysis mode in the sidebar to retry with Local or Template.]",
            f"{backend}-error",
        )
    return result["dossier"], "template"


def attach_analysis(result, backend):
    """Add the generative analysis to the result so it flows into dossier_json."""
    text, source = generate_dossier(result, backend)
    result["analysis"] = text
    result["analysis_source"] = source
    return result


# --------------------------------------------------------------------------- #
# Dashboard helpers
# --------------------------------------------------------------------------- #
_VERDICT_COLORS = {
    "Hidden Crisis": "#ef4444",
    "False Alarm":   "#f59e0b",
    "Consistent":    "#22c55e",
}

# The four pseudo-label signals the inferred severity is built from, with the
# fusion weights used in train_pipeline.py stage_fusion():
#     severity_fusion = 0.40*llm + 0.30*cluster + 0.20*resolution + 0.10*rule
# The DistilBERT model is trained on labels derived from this blend, so these
# weights are how much each signal contributes to the severity it infers. The
# LLM and cluster signals run only at training time (to build the labels) and
# are not recomputed per ticket at inference, so this panel reports the fusion
# weights rather than per-ticket signal values.
SIGNAL_WEIGHTS = {
    "LLM severity score":       0.40,
    "Embedding cluster score":  0.30,
    "Resolution-time score":    0.20,
    "Keyword rule score":       0.10,
}


def _dash_verdict_bar(df_r):
    """Mismatch type distribution bar chart."""
    counts = (
        df_r["mismatch_type"]
        .value_counts()
        .reindex(["Hidden Crisis", "False Alarm", "Consistent"])
        .fillna(0)
        .reset_index()
    )
    counts.columns = ["Verdict", "Count"]
    if _PLOTLY:
        fig = px.bar(
            counts, x="Verdict", y="Count",
            color="Verdict",
            color_discrete_map=_VERDICT_COLORS,
            title="Verdict Distribution",
            text="Count",
        )
        fig.update_traces(textposition="outside")
        fig.update_layout(showlegend=False, height=320,
                          margin=dict(t=50, b=20), yaxis_title="Tickets")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.bar_chart(counts.set_index("Verdict"))


def _dash_confidence_hist(df_r):
    """Confidence score histogram coloured by verdict."""
    if not _PLOTLY:
        st.caption("Install plotly for the confidence histogram.")
        return
    fig = px.histogram(
        df_r, x="confidence", nbins=20,
        color="mismatch_type",
        color_discrete_map=_VERDICT_COLORS,
        title="Confidence Score Distribution",
        labels={"confidence": "Model Confidence", "mismatch_type": "Verdict"},
        barmode="overlay",
    )
    fig.update_layout(height=320, bargap=0.05,
                      margin=dict(t=50, b=20),
                      legend_title_text="Verdict")
    st.plotly_chart(fig, use_container_width=True)


def _dash_signal_contributions(df_r):
    """Horizontal bar chart of the four pseudo-label signals that drive the
    inferred severity, sized by their fusion weight (llm 0.40, cluster 0.30,
    resolution 0.20, rule 0.10).

    Replaces the old per-keyword chart: keywords are only the rule-score
    component (10% of the blend), so a keyword frequency chart understated what
    actually drives the model. The inferred severity is a weighted blend of all
    four signals; this panel shows that blend."""
    sig_df = pd.DataFrame(
        {
            "Signal": list(SIGNAL_WEIGHTS.keys()),
            "Contribution": list(SIGNAL_WEIGHTS.values()),
        }
    )
    sig_df["Label"] = sig_df["Contribution"].map(lambda v: f"{v * 100:.0f}%")

    if _PLOTLY:
        fig = px.bar(
            sig_df, x="Contribution", y="Signal", orientation="h",
            title="Signal Contribution to Inferred Severity",
            color="Contribution",
            color_continuous_scale="Reds",
            text="Label",
        )
        fig.update_traces(textposition="outside", cliponaxis=False)
        fig.update_layout(
            showlegend=False,
            height=360,
            coloraxis_showscale=False,
            xaxis=dict(range=[0, 0.5], tickformat=".0%",
                       title="Weight in severity fusion"),
            yaxis=dict(autorange="reversed", title=""),  # largest weight on top
            margin=dict(l=200, r=60, t=50, b=40),
        )
        st.plotly_chart(fig, use_container_width=True)
    else:
        show = sig_df[["Signal", "Label"]].rename(columns={"Label": "Contribution"})
        st.dataframe(show, use_container_width=True, hide_index=True)


def _dash_heatmap(df_r):
    """Severity delta heatmap: category (rows) × channel (cols), avg delta as
    the cell value and colour. Positive = under-prioritised (red), negative =
    over-prioritised (blue)."""
    has_cat   = "category"       in df_r.columns and df_r["category"].str.strip().ne("").any()
    has_ch    = "channel"        in df_r.columns and df_r["channel"].str.strip().ne("").any()
    has_delta = "severity_delta" in df_r.columns

    if not (has_cat and has_ch and has_delta):
        st.info(
            "Category and channel columns are required for the heatmap. "
            "Score a batch CSV that includes those columns, or submit single "
            "tickets with category / channel filled in."
        )
        return

    if not _PLOTLY:
        st.info("Install plotly (`pip install plotly`) to render the heatmap.")
        return

    hm = df_r[
        df_r["category"].str.strip().ne("") & df_r["channel"].str.strip().ne("")
    ].copy()
    hm["severity_delta"] = pd.to_numeric(hm["severity_delta"], errors="coerce")
    hm = hm.dropna(subset=["severity_delta"])

    if hm.empty:
        st.info("No tickets with both category and channel data available yet.")
        return

    pivot_avg = (
        hm.groupby(["category", "channel"])["severity_delta"]
        .mean()
        .round(2)
        .unstack()
    )
    pivot_cnt = (
        hm.groupby(["category", "channel"])["severity_delta"]
        .count()
        .unstack()
        .reindex(index=pivot_avg.index, columns=pivot_avg.columns)
        .fillna(0)
        .astype(int)
    )

    if pivot_avg.shape[0] < 1 or pivot_avg.shape[1] < 1:
        st.info("Not enough category/channel combinations to build the heatmap yet.")
        return

    # Build annotation text: "avg_delta\n(n=count)"
    text_vals = []
    for i in range(pivot_avg.shape[0]):
        row_t = []
        for j in range(pivot_avg.shape[1]):
            v = pivot_avg.iloc[i, j]
            c = pivot_cnt.iloc[i, j]
            row_t.append(f"{v:.1f}<br>(n={c})" if not np.isnan(v) else "")
        text_vals.append(row_t)

    fig = go.Figure(data=go.Heatmap(
        z=pivot_avg.values,
        x=[str(c) for c in pivot_avg.columns],
        y=[str(r) for r in pivot_avg.index],
        colorscale="RdBu_r",
        zmid=0,
        zmin=-3,
        zmax=3,
        text=text_vals,
        texttemplate="%{text}",
        hovertemplate=(
            "Category: %{y}<br>"
            "Channel: %{x}<br>"
            "Avg Severity Delta: %{z:.2f}<extra></extra>"
        ),
        colorbar=dict(
            title=dict(text="Avg<br>Delta", side="right"),
            tickvals=[-3, -2, -1, 0, 1, 2, 3],
            ticktext=["−3", "−2", "−1", "0", "+1", "+2", "+3"],
            thickness=14,
        ),
    ))
    fig.update_layout(
        xaxis_title="Ticket Channel",
        yaxis_title="Issue Category",
        height=max(320, 56 * pivot_avg.shape[0] + 120),
        margin=dict(l=200, r=80, t=20, b=80),
    )
    st.plotly_chart(fig, use_container_width=True)

    col_l, col_m, col_r = st.columns(3)
    col_l.markdown(
        "<div class='heatmap-legend'>🔴 <b>Positive delta</b><br>"
        "Inferred severity > assigned → Hidden Crisis (under-prioritised)</div>",
        unsafe_allow_html=True,
    )
    col_m.markdown(
        "<div class='heatmap-legend'>⬜ <b>Zero delta</b><br>"
        "Inferred severity = assigned → Consistent</div>",
        unsafe_allow_html=True,
    )
    col_r.markdown(
        "<div class='heatmap-legend'>🔵 <b>Negative delta</b><br>"
        "Inferred severity < assigned → False Alarm (over-prioritised)</div>",
        unsafe_allow_html=True,
    )


# --------------------------------------------------------------------------- #
# Top navigation bar + inline mode selector
# --------------------------------------------------------------------------- #
st.markdown(
    """
    <div class="mars-navbar">
      <div>
        <div class="mars-logo">🎯 <span>MARS</span> · Ticket Priority Auditor</div>
        <div class="mars-tagline">Mismatch-Aware Re-ranking System &nbsp;·&nbsp; Detects Hidden Crisis &amp; False Alarm priorities</div>
      </div>
      <div class="mars-badge">v1.0</div>
    </div>
    """,
    unsafe_allow_html=True,
)

# ── Analysis mode selector (inline, above tabs) ──────────────────────────── #
with st.expander("⚙️  Analysis mode", expanded=False):
    col_mode, col_hint = st.columns([2, 3])
    with col_mode:
        options = list(BACKEND_LABELS.keys())
        default_idx = options.index(DEFAULT_BACKEND) if DEFAULT_BACKEND in options else 0
        backend = st.radio(
            "Dossier generation",
            options,
            index=default_idx,
            format_func=lambda x: BACKEND_LABELS[x],
            horizontal=True,
        )
    with col_hint:
        if backend == "mistral_api":
            if MISTRAL_API_KEY:
                st.info(f"✅  Using Mistral API · model: `{MISTRAL_API_MODEL}`")
            else:
                st.warning("⚠️  `MISTRAL_API_KEY` not set. Add it to Streamlit Secrets or switch to Template.")
        elif backend == "local_mistral":
            st.info("🖥️  Local Mistral 7B — only practical on a GPU machine.")
        else:
            st.info("⚡  Template mode — instant, deterministic, no LLM calls.")

tab_single, tab_batch, tab_summary = st.tabs(["🔍  Single Ticket", "📂  Batch CSV", "📊  Dashboard"])


# --------------------------------------------------------------------------- #
# Tab 1: single ticket
# --------------------------------------------------------------------------- #
with tab_single:
    with st.form("single_ticket"):
        c1, c2 = st.columns(2)
        with c1:
            ticket_id = st.text_input("Ticket ID (optional)", value="")
            category = st.selectbox("Issue category", CATEGORY_OPTS)
            priority = st.selectbox("Assigned priority", PRIORITY_OPTS)
        with c2:
            channel = st.selectbox("Ticket channel", CHANNEL_OPTS)
            resolution_hours = st.number_input(
                "Resolution time (hours)", min_value=0.0, value=24.0, step=1.0
            )

        subject = st.text_input("Ticket subject", value="")
        description = st.text_area("Ticket description", value="", height=140)
        submitted = st.form_submit_button("Analyze ticket", type="primary")

    if submitted:
        if not subject.strip() and not description.strip():
            st.info("Enter a subject or description first.")
        else:
            ticket = {
                "subject": subject,
                "description": description,
                "channel": channel,
                "category": category,
                "resolution_hours": resolution_hours,
                "priority": priority,
            }
            with st.spinner("Analyzing..."):
                result = predictor.predict(ticket)
                result = reconcile_verdict(result)
                result = attach_analysis(result, backend)
            tid = ticket_id.strip() or "MANUAL"
            row = result_to_row(tid, result)
            store_rows([row])

            verdict_banner(result["verdict"])

            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Ticket ID", tid)
            m2.metric("Prediction", row["prediction"])
            m3.metric("Confidence", f"{row['confidence'] * 100:.0f}%")
            m4.metric("Mismatch type", row["mismatch_type"])

            st.markdown("**Analysis**")
            st.write(result["analysis"])
            st.caption(f"Source: {result['analysis_source']}")

            with st.expander("dossier_json"):
                st.json(build_dossier_schema(tid, result))


# --------------------------------------------------------------------------- #
# Tab 2: batch CSV
# --------------------------------------------------------------------------- #
with tab_batch:
    st.write(
        "Upload a CSV of tickets. Recognized columns: Ticket_ID, "
        "Ticket_Subject, Ticket_Description, Issue_Category, Ticket_Channel, "
        "Priority_Level, Resolution_Time_Hours."
    )
    uploaded = st.file_uploader("Tickets CSV", type=["csv"])
    max_rows = st.number_input(
        "Rows to score (from the top)", min_value=1, value=200, step=50,
        help="Scoring runs on CPU, so a cap keeps it responsive. Raise it for full runs.",
    )
    gen_batch = st.checkbox(
        "Generate AI analysis for every row (uses the sidebar mode)",
        value=False,
        help="Off uses the instant template for every row (no LLM calls). "
             "On runs the selected sidebar mode once per row, which is much "
             "slower and, for Mistral API, uses your API quota.",
    )

    if uploaded is not None and st.button("Score CSV", type="primary"):
        df_in = pd.read_csv(uploaded)

        col_id       = find_col(df_in, ["Ticket_ID", "id"])
        col_subject  = find_col(df_in, ["Ticket_Subject", "subject"])
        col_desc     = find_col(df_in, ["Ticket_Description", "description"])
        col_channel  = find_col(df_in, ["Ticket_Channel", "channel"])
        col_category = find_col(df_in, ["Issue_Category", "category", "Ticket_Type"])
        col_priority = find_col(df_in, ["Priority_Level", "Ticket_Priority", "priority", "Assigned_Priority"])
        col_res      = find_col(df_in, ["Resolution_Time_Hours", "Resolution_Hours", "resolution_hours"])

        if col_subject is None and col_desc is None:
            st.error("No subject or description column found. Check the file headers.")
        else:
            df_use = df_in.head(int(max_rows))
            rows, errors = [], 0
            progress = st.progress(0.0, text="Scoring tickets...")
            total = len(df_use)

            for i, (_, r) in enumerate(df_use.iterrows()):
                try:
                    ticket = {
                        "subject":          str(r[col_subject])  if col_subject  else "",
                        "description":      str(r[col_desc])     if col_desc     else "",
                        "channel":          str(r[col_channel])  if col_channel  else "",
                        "category":         str(r[col_category]) if col_category else "",
                        "resolution_hours": r[col_res]           if col_res      else 0.0,
                        "priority":         str(r[col_priority]) if col_priority else "Low",
                    }
                    result = predictor.predict(ticket)
                    result = reconcile_verdict(result)
                    row_backend = backend if gen_batch else "template"
                    result = attach_analysis(result, row_backend)
                    tid = str(r[col_id]) if col_id else f"ROW-{i + 1}"
                    rows.append(result_to_row(tid, result))
                except Exception:  # noqa: BLE001
                    errors += 1
                progress.progress((i + 1) / total, text=f"Scored {i + 1} of {total}")

            progress.empty()

            if rows:
                out_df = pd.DataFrame(rows, columns=OUTPUT_COLS)
                store_rows(rows)
                st.success(f"Scored {len(rows)} tickets" + (f", skipped {errors}." if errors else "."))
                st.dataframe(out_df, use_container_width=True, hide_index=True)
                st.download_button(
                    "Download results CSV",
                    out_df.to_csv(index=False).encode("utf-8"),
                    file_name="ticket_audit_results.csv",
                    mime="text/csv",
                )
            else:
                st.error("No rows could be scored.")


# --------------------------------------------------------------------------- #
# Tab 3: Priority Mismatch Dashboard
# --------------------------------------------------------------------------- #
with tab_summary:
    results = st.session_state.get("results")

    if results is None or results.empty:
        st.info(
            "Score a ticket or upload a CSV first — this Dashboard fills in "
            "automatically once data are available."
        )
    else:
        df_r = results.copy()

        # Ensure severity_delta is numeric (guard against older session rows)
        if "severity_delta" in df_r.columns:
            df_r["severity_delta"] = pd.to_numeric(df_r["severity_delta"], errors="coerce")

        total       = len(df_r)
        n_mismatch  = int((df_r["prediction"] == "Mismatch").sum())
        n_hidden    = int((df_r["mismatch_type"] == "Hidden Crisis").sum())
        n_false     = int((df_r["mismatch_type"] == "False Alarm").sum())
        n_consistent = int((df_r["mismatch_type"] == "Consistent").sum())
        mismatch_pct = f"{n_mismatch / total * 100:.1f} %" if total > 0 else "—"

        # ── Overview metrics ──────────────────────────────────────────────── #
        m1, m2, m3, m4, m5 = st.columns(5)
        m1.metric("Tickets Scored", total)
        m2.metric("Mismatches",     n_mismatch,   delta=mismatch_pct, delta_color="inverse")
        m3.metric("🔴 Hidden Crisis", n_hidden)
        m4.metric("🟡 False Alarm",   n_false)
        m5.metric("✅ Consistent",    n_consistent)

        st.divider()

        # ── Row 1: Verdict distribution + Confidence histogram ────────────── #
        st.subheader("Priority Mismatch Distribution")
        col_bar, col_hist = st.columns(2)
        with col_bar:
            _dash_verdict_bar(df_r)
        with col_hist:
            _dash_confidence_hist(df_r)

        st.divider()

        # ── Row 2: Signal contributions to inferred severity ──────────────── #
        st.subheader("Top Contributing Signals")
        st.caption(
            "The four signals the inferred severity is built from — LLM "
            "severity, embedding-cluster score, resolution time, and the "
            "keyword rule score — sized by their weight in the training fusion. "
            "The LLM and cluster signals are computed during training to build "
            "the severity labels; at inference the model reproduces that blend "
            "rather than recomputing each signal per ticket."
        )
        _dash_signal_contributions(df_r)

        st.divider()

        # ── Row 3: Severity delta heatmap ─────────────────────────────────── #
        st.subheader("Severity Delta Heatmap — Category × Channel")
        st.caption(
            "Average (inferred severity − assigned priority) per cell. "
            "Positive values (red) → tickets are likely under-prioritised. "
            "Negative values (blue) → tickets are likely over-prioritised."
        )
        _dash_heatmap(df_r)

        st.divider()

        # ── Row 4: Scored tickets table ───────────────────────────────────── #
        st.subheader("Scored Tickets")
        only_mismatch = st.checkbox("Show mismatches only", value=True)

        # Show a curated column set; omit dossier_json (too wide for the table)
        display_cols = [c for c in [
            "Ticket_ID", "prediction", "confidence", "mismatch_type",
            "severity_delta", "category", "channel",
        ] if c in df_r.columns]

        view = df_r[df_r["prediction"] == "Mismatch"] if only_mismatch else df_r
        st.dataframe(view[display_cols], use_container_width=True, hide_index=True)

        dl_col, clr_col = st.columns([3, 1])
        with dl_col:
            st.download_button(
                "Download all results CSV",
                df_r.to_csv(index=False).encode("utf-8"),
                file_name="ticket_audit_session.csv",
                mime="text/csv",
            )
        with clr_col:
            if st.button("Clear results"):
                st.session_state.pop("results", None)
                st.rerun()
